# Start with a Gradle image for the build process
FROM gradle:7.2-jdk11 AS build
WORKDIR /app
COPY . .

# Build the application
RUN gradle clean build

# Now, move to the second stage with an OpenJDK image
FROM openjdk:11-jdk

# Copy the built JAR file from the builder
COPY --from=build /app/build/libs/*.jar /app/app.jar

# Expose the necessary port
EXPOSE 8080

# Define the startup command that will run your app
ENTRYPOINT ["java", "-jar", "/app/app.jar"]