#!/bin/bash
docker run -it -v $(pwd):/workspace:cached -w /workspace -v gradle-cache:/home/gradle/.gradle gradle gradle clean build
docker build --pull --label org.label-schema.vcs-ref=$(git rev-parse HEAD) -t spring_helloworld: .latest
docker run -p8080:8080 spring_helloworld
