apiVersion: v1
kind: Service
metadata:
  name: spring-hello-world-example-service
spec:
  type: NodePort
  selector:
    app: spring-hello-world-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000